const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      description: 'high quality shirt',      
      image: '/images/p1.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 10,
      weight: 1,
      currentPrice: 120, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available',
      productCategory: 'Shirts',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      description: 'high quality product',      
      image: '/images/p2.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 5,
      weight: 1,
      currentPrice: 250, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Shirts',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      description: 'high quality product',      
      image: '/images/p3.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 20,
      weight: 2,
      currentPrice: 50, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Pants',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      description: 'high quality shirt',      
      image: '/images/p4.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 10,
      weight: 2,
      currentPrice: 100, 
      discountedPrice: 5, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Pants',
    },
  ],
};
export default data;
