import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'Rohan',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
    {
      name: 'John',
      email: 'customer@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      description: 'high quality shirt',      
      image: '/images/p1.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 10,
      weight: 1,
      currentPrice: 120, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available',
      productCategory: 'Shirts',         
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      description: 'high quality product',      
      image: '/images/p2.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 5,
      weight: 1,
      currentPrice: 250, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Shirts',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      description: 'high quality product',      
      image: '/images/p3.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 20,
      weight: 2,
      currentPrice: 50, 
      discountedPrice: 0, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Pants',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      description: 'high quality shirt',      
      image: '/images/p4.jpg',
      unitOfMeasure: 'metre',
      quantityOnHand: 10,
      weight: 2,
      currentPrice: 100, 
      discountedPrice: 5, 
      isFeatured: true,   
      productStatus: 'Available', 
      productCategory: 'Pants',
    },
  ],
};
export default data;
